services:
  postgres:
    image: postgres:17
    container_name: local-postgres
    ports:
      - "1234:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Hus@334nt
      POSTGRES_DB: storage_event

    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shared_network

networks:
  shared_network:
    external: true